# ---- Build ----
FROM mirror.gcr.io/library/node:20-alpine AS build
#FROM public.ecr.aws/docker/library/node:20-alpine AS build
#FROM node:20-alpine AS build
WORKDIR /app

# 1) Dependencias (cache)
COPY package*.json ./
RUN npm ci

# 2) Vars de build para Vite
ARG VITE_API_BASE=""
ARG VITE_GOOGLE_MAPS_API_KEY=""

# 3) Código
COPY . .

# 4) .env para Vite (si ya tienes otro flujo, puedes quitar esto)
RUN printf "VITE_API_BASE=%s\nVITE_GOOGLE_MAPS_API_KEY=%s\n" \
    "$VITE_API_BASE" "$VITE_GOOGLE_MAPS_API_KEY" > .env

# 5) Build
RUN npm run build

# ---- Runtime (Nginx) ----
FROM mirror.gcr.io/library/nginx:1.27-alpine
#FROM public.ecr.aws/nginx/nginx:1.25-alpine
#FROM nginx:1.27-alpine
# curl para healthcheck del contenedor
RUN apk add --no-cache curl

# Usa el conf de AWS por defecto (puedes cambiarlo con ARG si quieres)
ARG NGINX_CONF=nginx.aws.conf
COPY ${NGINX_CONF} /etc/nginx/conf.d/default.conf

# Estáticos
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
# La imagen oficial ya usa "nginx -g 'daemon off;'", así que no hace falta CMD.