server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  # Tamaño máximo de subida (ajústalo si necesitas más)
  client_max_body_size 50M;

  # Healthcheck para ECS/ALB
  location = /healthz {
    return 200 'ok';
    add_header Content-Type text/plain;
  }

  # SPA: sirve index.html para rutas que no existan
  location / {
    try_files $uri $uri/ /index.html;
  }
}