services:
  backend:
    platform: linux/amd64
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
  frontend:
    platform: linux/amd64
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend