"""Add city, country, postcode to sites

Revision ID: 4d40ee115438
Revises: f7859a6ca02c
Create Date: 2025-04-12 20:44:07.534342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d40ee115438'
down_revision: Union[str, None] = 'f7859a6ca02c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('city', sa.String(), nullable=True))
    op.add_column('sites', sa.Column('country', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'country')
    op.drop_column('sites', 'city')
    # ### end Alembic commands ###
