"""Add postcode to sites

Revision ID: 63d7b6d09a47
Revises: 4d40ee115438
Create Date: 2025-04-12 21:16:37.521976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63d7b6d09a47'
down_revision: Union[str, None] = '4d40ee115438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('postcode', sa.String(), nullable=True))
    op.drop_column('sites', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('location', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('sites', 'postcode')
    # ### end Alembic commands ###
