"""update geonames_cities schema

Revision ID: 979676760f8c
Revises: 9e4ac666b53b
Create Date: 2025-04-12 18:29:23.420094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '979676760f8c'
down_revision: Union[str, None] = '9e4ac666b53b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('geonames_cities', sa.Column('alternatenames', sa.String(), nullable=True))
    op.add_column('geonames_cities', sa.Column('feature_class', sa.String(), nullable=True))
    op.add_column('geonames_cities', sa.Column('feature_code', sa.String(), nullable=True))
    op.add_column('geonames_cities', sa.Column('cc2', sa.String(), nullable=True))
    op.add_column('geonames_cities', sa.Column('admin2_code', sa.String(), nullable=True))
    op.add_column('geonames_cities', sa.Column('admin3_code', sa.String(), nullable=True))
    op.add_column('geonames_cities', sa.Column('admin4_code', sa.String(), nullable=True))
    op.add_column('geonames_cities', sa.Column('elevation', sa.String(), nullable=True))
    op.add_column('geonames_cities', sa.Column('dem', sa.String(), nullable=True))
    op.add_column('geonames_cities', sa.Column('timezone', sa.String(), nullable=True))
    op.add_column('geonames_cities', sa.Column('modification_date', sa.String(), nullable=True))
    op.alter_column('geonames_cities', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('geonames_cities', 'population',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('geonames_cities', 'population',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('geonames_cities', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('geonames_cities', 'modification_date')
    op.drop_column('geonames_cities', 'timezone')
    op.drop_column('geonames_cities', 'dem')
    op.drop_column('geonames_cities', 'elevation')
    op.drop_column('geonames_cities', 'admin4_code')
    op.drop_column('geonames_cities', 'admin3_code')
    op.drop_column('geonames_cities', 'admin2_code')
    op.drop_column('geonames_cities', 'cc2')
    op.drop_column('geonames_cities', 'feature_code')
    op.drop_column('geonames_cities', 'feature_class')
    op.drop_column('geonames_cities', 'alternatenames')
    # ### end Alembic commands ###
