"""Add latitude and longitude to sites table

Revision ID: f7859a6ca02c
Revises: 979676760f8c
Create Date: 2025-04-12 20:00:48.139290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7859a6ca02c'
down_revision: Union[str, None] = '979676760f8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('sites', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'longitude')
    op.drop_column('sites', 'latitude')
    # ### end Alembic commands ###
